import { Inter, Lalezar } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'

const bodyFont = Inter({ subsets: ['latin'] })
const lalezar = Lalezar({ 
    subsets: ['arabic'], 
    weight: ['400'], 
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>

        
        <div className=''>
        <Navbar />
        <h1 className={lalezar.className}>
          محتوى عربي ..
        </h1>
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
